#ifndef SPRINGLOBBY_HEADERGUARD_VERSIONCHECKER_H
#define SPRINGLOBBY_HEADERGUARD_VERSIONCHECKER_H

#include <wx/string.h>

wxString GetLatestVersion();

#endif // SPRINGLOBBY_HEADERGUARD_VERSIONCHECKER_H
