#ifndef __simplefront__
#define __simplefront__

/**
@file
Subclass of SimpleFrontBase, which is generated by wxFormBuilder.
*/

class settings_frame;
class SkirmishDialog;

#include "simplefrontbase.h"

/** Implementing SimpleFrontBase */
class SimpleFront : public SimpleFrontBase
{
protected:
	// Handlers for SimpleFrontBase events.
	void OnSingleplayer( wxCommandEvent& event );
	void OnMultiplayer( wxCommandEvent& event );
	void OnSettings( wxCommandEvent& event );
	void OnExit( wxCommandEvent& event );
	void OnSkipChecked( wxCommandEvent& event );

	void Close();

	settings_frame* m_settings;
	SkirmishDialog* m_skirmish;

public:
	/** Constructor */
	SimpleFront( wxWindow* parent );
};

#endif // __simplefront__
