#! /bin/sh

DIR_DEBUG="build-CMake/Debug"
CMAKE_OPTIONS="
-DCMAKE_COLOR_MAKEFILE:BOOL=ON
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
-DCMAKE_BUILD_TYPE:STRING=RELEASE
-DBUILD_SHARED_LIBS:BOOL=ON
"

mkdir -p "${DIR_DEBUG}"
cd "${DIR_DEBUG}"

cmake "${CMAKE_OPTIONS}"  ../../