#!/bin/bash
# This script autogenerates a flagimages.h file
#

echo "//"
echo "// flagimages.h"
echo "// (autogenerated from mkflaghead.sh)"
echo "//"
echo
echo \#ifndef _FLAGIMAGES_H_
echo \#define _FLAGIMAGES_H_
echo
for img in `ls *.xpm`
do
#  convert -page 25x25+0+4 -mosaic $img -crop 25x25\! -delete 1 -resize 16x16 $img.xpm
  echo \#include \"images/flags/`echo $img`\"
#`echo $img | sed s/.xpm/""/`\"
done
echo
echo "int GetFlagIndex( const std::string& flag );"
echo
echo "static char* flag_str[] = {"
echo "  "
for img in `ls *.xpm`
do
  echo -n "\"`echo $img | sed s/.xpm/""/`\","
done

echo "\"\""
echo "};"

echo
echo "enum {"
echo "  FLAG_NONE = -1,"

for img in `ls *.xpm`
do
  echo -n "FLAG_`echo $img | sed s/.xpm/""/`,"
done

echo "FLAG_LAST"
echo "};"
echo

echo -n "#define ADD_FLAGS_IMAGES(il) "

for img in `ls *.xpm`
do
  echo -n "il->Add(wxBITMAP(`echo $img | sed s/.xpm/""/`));"
done

echo
echo
echo \#endif
echo
