Document: springlobby
Title: Debian springlobby Manual
Author: <insert document author here>
Abstract: This manual describes what springlobby is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/springlobby/springlobby.sgml.gz

Format: postscript
Files: /usr/share/doc/springlobby/springlobby.ps.gz

Format: text
Files: /usr/share/doc/springlobby/springlobby.text.gz

Format: HTML
Index: /usr/share/doc/springlobby/html/index.html
Files: /usr/share/doc/springlobby/html/*.html

  
