#!/usr/bin/env bash

set -e
cd $(dirname $0)/..

function create-build-dir ()
{
	(
	if [ ! -d $1 ] ; then
		mkdir $1
		cd $1
		../configure --config-cache $2
	fi
	)
}

create-build-dir build
create-build-dir build-linux-wx28 --with-wx-config=/var/lib/buildbot/lib/linux/wx/2.8/bin/wx-config
create-build-dir build-mingw-wx28 "--build=i686-pc-linux-gnu --host=i586-mingw32msvc --with-wx-config=/var/lib/buildbot/lib/mingw/wx/2.8/bin/wx-config"

