#ifndef SPRINGLOBBY_HEADERGUARD_COUNTRYCODES_H
#define SPRINGLOBBY_HEADERGUARD_COUNTRYCODES_H

class wxString;

wxString GetFlagNameFromCountryCode( const wxString& cc );

#endif // SPRINGLOBBY_HEADERGUARD_COUNTRYCODES_H
