SET(libtorrent_SOURCE_DIR src/libtorrent/src)
SET(libtorrent_DIR src/libtorrent)
SET(libtorrent_SRC 
	${libtorrent_SOURCE_DIR}/entry.cpp
	${libtorrent_SOURCE_DIR}/escape_string.cpp
	${libtorrent_SOURCE_DIR}/assert.cpp
	${libtorrent_SOURCE_DIR}/enum_net.cpp
	${libtorrent_SOURCE_DIR}/broadcast_socket.cpp
	${libtorrent_SOURCE_DIR}/peer_connection.cpp
	${libtorrent_SOURCE_DIR}/bt_peer_connection.cpp
	${libtorrent_SOURCE_DIR}/web_peer_connection.cpp
	${libtorrent_SOURCE_DIR}/natpmp.cpp
	${libtorrent_SOURCE_DIR}/piece_picker.cpp
	${libtorrent_SOURCE_DIR}/policy.cpp
	${libtorrent_SOURCE_DIR}/session.cpp
	${libtorrent_SOURCE_DIR}/session_impl.cpp
	${libtorrent_SOURCE_DIR}/sha1.cpp
	${libtorrent_SOURCE_DIR}/stat.cpp
	${libtorrent_SOURCE_DIR}/storage.cpp
	${libtorrent_SOURCE_DIR}/torrent.cpp
	${libtorrent_SOURCE_DIR}/torrent_handle.cpp
	${libtorrent_SOURCE_DIR}/pe_crypto.cpp
	${libtorrent_SOURCE_DIR}/torrent_info.cpp
	${libtorrent_SOURCE_DIR}/tracker_manager.cpp
	${libtorrent_SOURCE_DIR}/http_connection.cpp
	${libtorrent_SOURCE_DIR}/http_tracker_connection.cpp
	${libtorrent_SOURCE_DIR}/udp_tracker_connection.cpp
	${libtorrent_SOURCE_DIR}/alert.cpp
	${libtorrent_SOURCE_DIR}/identify_client.cpp
	${libtorrent_SOURCE_DIR}/ip_filter.cpp
	${libtorrent_SOURCE_DIR}/file.cpp
	${libtorrent_SOURCE_DIR}/metadata_transfer.cpp
	${libtorrent_SOURCE_DIR}/logger.cpp
	${libtorrent_SOURCE_DIR}/file_pool.cpp
	${libtorrent_SOURCE_DIR}/ut_pex.cpp
	${libtorrent_SOURCE_DIR}/lsd.cpp
	${libtorrent_SOURCE_DIR}/upnp.cpp
	${libtorrent_SOURCE_DIR}/instantiate_connection.cpp
	${libtorrent_SOURCE_DIR}/socks5_stream.cpp
	${libtorrent_SOURCE_DIR}/socks4_stream.cpp
	${libtorrent_SOURCE_DIR}/http_stream.cpp
	${libtorrent_SOURCE_DIR}/connection_queue.cpp
	${libtorrent_SOURCE_DIR}/disk_io_thread.cpp

	${libtorrent_SOURCE_DIR}/kademlia/closest_nodes.cpp
	${libtorrent_SOURCE_DIR}/kademlia/dht_tracker.cpp
	${libtorrent_SOURCE_DIR}/kademlia/find_data.cpp
	${libtorrent_SOURCE_DIR}/kademlia/node.cpp
	${libtorrent_SOURCE_DIR}/kademlia/node_id.cpp
	${libtorrent_SOURCE_DIR}/kademlia/refresh.cpp
	${libtorrent_SOURCE_DIR}/kademlia/routing_table.cpp
	${libtorrent_SOURCE_DIR}/kademlia/rpc_manager.cpp
	${libtorrent_SOURCE_DIR}/kademlia/traversal_algorithm.cpp

	${libtorrent_DIR}/zlib/adler32.c
	${libtorrent_DIR}/zlib/compress.c
	${libtorrent_DIR}/zlib/crc32.c
	${libtorrent_DIR}/zlib/deflate.c
	${libtorrent_DIR}/zlib/gzio.c
	${libtorrent_DIR}/zlib/infback.c
	${libtorrent_DIR}/zlib/inffast.c
	${libtorrent_DIR}/zlib/inflate.c
	${libtorrent_DIR}/zlib/inftrees.c
	${libtorrent_DIR}/zlib/trees.c
	${libtorrent_DIR}/zlib/uncompr.c
	${libtorrent_DIR}/zlib/zutil.c 
)